"""Initial schema

Revision ID: f99c672f269e
Revises: 
Create Date: 2025-12-20 19:40:59.028308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99c672f269e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('buyer_name', sa.String(), nullable=False))
    op.add_column('payment_transactions', sa.Column('device_count', sa.Integer(), nullable=True))
    op.drop_column('payment_transactions', 'email')
    op.add_column('users', sa.Column('auto_generated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tx_ref', sa.String(), nullable=True))
    op.add_column('users', sa.Column('device_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_count')
    op.drop_column('users', 'tx_ref')
    op.drop_column('users', 'buyer_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'auto_generated')
    op.add_column('payment_transactions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payment_transactions', 'device_count')
    op.drop_column('payment_transactions', 'buyer_name')
    # ### end Alembic commands ###
